# Pete Nelson, PhD
# Department of Water Resources
# project: drought traits (special studies)
# purpose: complete fourth-corner & RLQ tutorial
# from: Dray et al. 2014
# created: 2023-05-18
# last modified: 2023-06-05

# getting started -----

library(ade4)
data(aravo)

dim(aravo$spe) # 75 sites and 82 spp
dim(aravo$env) # each site per each of 6 environmental variables (aspect, slope, snow, etc)
dim(aravo$traits) # each spp described by 8 traits (height, spread, seed, etc)

# RLQ -----

## separate analysis for each table ----
afcL.aravo <- 
  dudi.coa(aravo$spe,   # correspondence analysis applied to spp table
           scannf = F)

acpR.aravo <- 
  dudi.hillsmith(   # environ data include both quantitative & categorical variables, thus dudi.hillsmith
    aravo$env, 
    row.w = afcL.aravo$lw,
    scannf = F)

acpQ.aravo <- dudi.pca(  # all trait variables are quantitative thus pca
  aravo$traits, 
  row.w = afcL.aravo$cw,
  scannf = F)

## combine spp-env-traits -----
rlq.aravo <-
  rlq(acpR.aravo, afcL.aravo, acpQ.aravo,
      scannf = F)

# RLQ analysis finds coefficients in $c1 to obtain a linear combo of traits (spp scores in $1Q) and coefficients (in $l1) to obtain a linear combo of env variables (site scores in $1R). The covariance btwn these 2 set scores is maximized and equal to the square root of the corresponding eigenvalue.

## plot results ----
plot(rlq.aravo)

# Plot figures separately as follows:
par(mfrow = c(1, 3)) 
s.arrow(rlq.aravo$l1) 
s.arrow(rlq.aravo$c1) 
s.label(rlq.aravo$lQ, boxes = FALSE)

# Some of the ugliest figures in existence!

dev.off()

# It's important to see how the individual parts (ie cov(traits, env)^2 = var(traits) x var(env) x cor(traits, env)^2) of the compromise are considered. Hence, compare the RLQ analyusis to the separate analyses which maximize independently the structure of the trait (pca traits), structure of the environment (Hill-Smith analysis environmental variables) and correlation (correspondence analysis of the sites-spp table). Comparisons provided summary function:

summary(rlq.aravo)
# Note: correlation is quite low for second axis (0.2753). Variance of the env scores is well preserved on the first 2 axes (acpR.aravo: 89.53%). Traits, amount of variance preserved (2.341 & 3.667) in nearly equal to amount obtained in simple pca (2.409 & 3.907). 

# Fourth-corner ----
# Analysis tests associations btwn individual traits and environmental variables. To obtain test w correct type I error, results of model 2 (permutation of sites, ie rows) and 4 (permutation of spp, ie columns) should be combined. While the former version of ade4 required three steps (tests w the two models and combination of the results), the combined approach can now be generated by setting the modeltype argument to 6. Note that we used a very high number of repetitions (nrepet <- 49999) to have enough power in corrected tests. This time-consuming and could be modified to speed up the different analyses (eg nrepet <- 999, the default setting).

nrepet <- 999 # takes a few seconds only
four.comb.aravo <- fourthcorner(
  aravo$env, aravo$spe, aravo$traits,
  modeltype = 6,
  p.adjust.method.G = "none",
  p.adjust.method.D = "none",
  nrepet = nrepet
)

# When you plot the results, blue cells correspond to negative significant relationships while red cells correspond to positive ones (modify using argument col). In this example, there are some associations btwn categorical traits and quantitative environmental variables which can be measured in three different ways (Legendre et al 1997). These three mehtods correspond to three possible values of the stat argument in the plot and print functions:
# stat="D2": association is measured btwn quantitataive variable and each category separately. A correlation coefficient is used to indicate the strength of teh association between the given category and the small or large values of the quantaitative variable.
# stat="G": the association btwn the quantaitative variable and the whole categorical variable is measured by a global statsistic (F)
# stat="D": association is estimated btwn the quantitative variable and each category separately by a measure of the within-group homogeneity. The strength of the association is indicated by the dispersion of the values of the quantitative variable for a given category.
# In the rest of the tutorial, the focus is on the D2 statistic. The correction of p-values by a sequential procedure leads to significant associations if the maximal p-value is lower than alpha=0.05. When alpha=0.05, there are only 26 significan associations.

plot(four.comb.aravo, alpha = 0.05, stat = "D2")

# Now, adjust p-values for multiple comparisons using the fdr method using the p.adjust.4thcorner function (assuming nrepet set to 49999, though I got the same results with nrepet=9999).

four.comb.aravo.adj <-
  p.adjust.4thcorner(
    four.comb.aravo,
    p.adjust.method.G = "fdr",
    p.adjust.method.D = "fdr"
  )
# Adjusted p-values can be obtained directly using the fourthcorner function:
fourthcorner(aravo$env, aravo$spe, aravo$traits,
             modeltype = 6,
             p.adjust.method.G = "fdr",
             p.adjust.method.D = "fdr",
             nrepet = nrepet)

plot(four.comb.aravo.adj,
     alpha = 0.05,
     stat = "D2")

# 4th+RLQ ----

## trait X env -----

# First evaluate the global significance of the traits-environment relationships using test based on total inertia of the RLQ analysis:
testrlq.aravo <- 
  randtest(rlq.aravo,
           modeltype = 6,
           nrepet = nrepet)
testrlq.aravo

plot(testrlq.aravo)

# Total inertia of RLQ analysis is equal to the S(RLQ) multivariate statistic defined in Dray & Legrende (2008). this stat is returned by fourthcorner2 function:
Srlq <- fourthcorner2(
  aravo$env, aravo$spe, aravo$traits,
  modeltype = 6,
  p.adjust.method.G = "fdr",
  nrepet = nrepet
)
Srlq$trRLQ

# Both approaches can be combined if RLQ scores are used to represent traits and environmental variables on a biplot. Then, significant associations revealed by the 4thcorner approach can be represented using segments (blue for neg, red for pos, see argument col). Only traits and environmental variables that have at least one significant association are reprresented. Here, we apply this method using adjusted p-values for multiple comparisons and alpha=0.05.

plot(four.comb.aravo.adj, 
     x.rlq = rlq.aravo, 
     alpha = 0.05,
     stat = "D2",
     type = "biplot")

# Whew! Not easily interpreted at first glance!

# Another approach is provided by the fourthcorner.rlq function and consists of testing directly the links btwn RLQ axes and traits (typetest = "Q.axes") or environmental variables (typetest = "R.axes").

testQaxes.comb.aravo <-
  fourthcorner.rlq(rlq.aravo,
                   modeltype = 6,
                   typetest = "Q.axes",
                   nrepet = nrepet,
                   p.adjust.method.G = "fdr",
                   p.adjust.method.D = "fdr")

testRaxes.comb.aravo <-
  fourthcorner.rlq(rlq.aravo,
                   modeltype = 6,
                   typetest = "R.axes",
                   nrepet = nrepet,
                   p.adjust.method.G = "fdr",
                   p.adjust.method.D = "fdr")

print(testQaxes.comb.aravo, stat = "D")
print(testRaxes.comb.aravo, stat = "D")

# Present result in table format with colors to indicate significance:
par(mfrow = c(1, 2))
plot(testQaxes.comb.aravo,
     alpha = 0.05,
     type = "table",
     stat = "D2")
plot(testRaxes.comb.aravo,
     alpha = 0.05,
     type = "table",
     stat = "D2")

# Significance with axes can also be reported on the factorial map of RLQ analysis. Here, significant associations with the first axis are in blue, with the 2nd axis in orange, and both axes in green (variables w no significant association in black):

par(mfrow = c(1, 2))
plot(testQaxes.comb.aravo,
     alpha = 0.05,
     type = "biplot",
     stat = "D2",
     col = c("black", "blue", "orange", "green"))
plot(testRaxes.comb.aravo,
     alpha = 0.05,
     type = "biplot",
     stat = "D2",
     col = c("black", "blue", "orange", "green"))
par(mfrow = c(1, 1))
